// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutPlanner.API.Data;

#nullable disable

namespace WorkoutPlanner.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260531155845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutPlanner.API.Models.Equipment", b =>
                {
                    b.Property<int>("IdEquipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipment"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEquipment");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            IdEquipment = 1,
                            Description = "No equipment",
                            IsActive = true,
                            Name = "None"
                        },
                        new
                        {
                            IdEquipment = 2,
                            Description = "Pair of dumbbells",
                            IsActive = true,
                            Name = "Dumbbells"
                        },
                        new
                        {
                            IdEquipment = 3,
                            Description = "Elastic training band",
                            IsActive = true,
                            Name = "Resistance Band"
                        });
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.Exercise", b =>
                {
                    b.Property<int>("IdExercise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExercise"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEquipment")
                        .HasColumnType("int");

                    b.Property<int>("IdExerciseCategory")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdExercise");

                    b.HasIndex("IdEquipment");

                    b.HasIndex("IdExerciseCategory");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            IdExercise = 1,
                            Description = "Lower body strength exercise",
                            IdEquipment = 1,
                            IdExerciseCategory = 1,
                            IsActive = true,
                            Name = "Squats"
                        },
                        new
                        {
                            IdExercise = 2,
                            Description = "Cardio running session",
                            IdEquipment = 1,
                            IdExerciseCategory = 2,
                            IsActive = true,
                            Name = "Running"
                        },
                        new
                        {
                            IdExercise = 3,
                            Description = "Mobility and flexibility work",
                            IdEquipment = 1,
                            IdExerciseCategory = 3,
                            IsActive = true,
                            Name = "Stretching"
                        });
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.ExerciseCategory", b =>
                {
                    b.Property<int>("IdExerciseCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExerciseCategory"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdExerciseCategory");

                    b.ToTable("ExerciseCategories");

                    b.HasData(
                        new
                        {
                            IdExerciseCategory = 1,
                            Description = "Strength exercises",
                            IsActive = true,
                            Name = "Strength"
                        },
                        new
                        {
                            IdExerciseCategory = 2,
                            Description = "Cardio exercises",
                            IsActive = true,
                            Name = "Cardio"
                        },
                        new
                        {
                            IdExerciseCategory = 3,
                            Description = "Mobility exercises",
                            IsActive = true,
                            Name = "Mobility"
                        });
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.Goal", b =>
                {
                    b.Property<int>("IdGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGoal"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdGoal");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            IdGoal = 1,
                            Description = "Improve endurance and run 10 km comfortably",
                            IsActive = true,
                            Name = "Run 10 km",
                            TargetDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.ProgressEntry", b =>
                {
                    b.Property<int>("IdProgressEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgressEntry"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdWorkoutPlan")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProgressEntry");

                    b.HasIndex("IdWorkoutPlan");

                    b.ToTable("ProgressEntries");

                    b.HasData(
                        new
                        {
                            IdProgressEntry = 1,
                            DurationMinutes = 45,
                            EntryDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdWorkoutPlan = 1,
                            IsActive = true,
                            Notes = "Good training"
                        });
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.UserProfile", b =>
                {
                    b.Property<int>("IdUserProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserProfile"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUserProfile");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            IdUserProfile = 1,
                            Email = "demo@example.com",
                            IsActive = true,
                            Name = "Demo User"
                        });
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("IdWorkoutPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWorkoutPlan"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUserProfile")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdWorkoutPlan");

                    b.HasIndex("IdUserProfile");

                    b.ToTable("WorkoutPlans");

                    b.HasData(
                        new
                        {
                            IdWorkoutPlan = 1,
                            Description = "Focus on lower body strength.",
                            IdUserProfile = 1,
                            IsActive = true,
                            Name = "Leg Day"
                        },
                        new
                        {
                            IdWorkoutPlan = 2,
                            Description = "High intensity cardio session.",
                            IdUserProfile = 1,
                            IsActive = true,
                            Name = "Cardio Blast"
                        });
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.WorkoutPlanExercise", b =>
                {
                    b.Property<int>("IdWorkoutPlanExercise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWorkoutPlanExercise"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("IdExercise")
                        .HasColumnType("int");

                    b.Property<int>("IdWorkoutPlan")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.HasKey("IdWorkoutPlanExercise");

                    b.HasIndex("IdExercise");

                    b.HasIndex("IdWorkoutPlan");

                    b.ToTable("WorkoutPlanExercises");

                    b.HasData(
                        new
                        {
                            IdWorkoutPlanExercise = 1,
                            IdExercise = 1,
                            IdWorkoutPlan = 1,
                            OrderNumber = 1,
                            Reps = 10,
                            Sets = 4
                        },
                        new
                        {
                            IdWorkoutPlanExercise = 2,
                            DurationSeconds = 1800,
                            IdExercise = 2,
                            IdWorkoutPlan = 2,
                            OrderNumber = 1,
                            Reps = 1,
                            Sets = 1
                        });
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.Exercise", b =>
                {
                    b.HasOne("WorkoutPlanner.API.Models.Equipment", "Equipment")
                        .WithMany("Exercises")
                        .HasForeignKey("IdEquipment")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorkoutPlanner.API.Models.ExerciseCategory", "ExerciseCategory")
                        .WithMany("Exercises")
                        .HasForeignKey("IdExerciseCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ExerciseCategory");
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.ProgressEntry", b =>
                {
                    b.HasOne("WorkoutPlanner.API.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("IdWorkoutPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.WorkoutPlan", b =>
                {
                    b.HasOne("WorkoutPlanner.API.Models.UserProfile", "UserProfile")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("IdUserProfile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.WorkoutPlanExercise", b =>
                {
                    b.HasOne("WorkoutPlanner.API.Models.Exercise", "Exercise")
                        .WithMany("WorkoutPlanExercises")
                        .HasForeignKey("IdExercise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutPlanner.API.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutPlanExercises")
                        .HasForeignKey("IdWorkoutPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.Equipment", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutPlanExercises");
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.ExerciseCategory", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.UserProfile", b =>
                {
                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("WorkoutPlanner.API.Models.WorkoutPlan", b =>
                {
                    b.Navigation("ProgressEntries");

                    b.Navigation("WorkoutPlanExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
